name: Extract ISO and Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y wget libarchive-tools squashfs-tools jq

      - name: Create directories
        run: mkdir -p iso source-iso

      - name: Download latest ISO from GitHub Release
        run: |
          set -e

          REPO="RengeOS/Source-ISO"
          echo "Fetching latest release info..."
          API_URL="https://api.github.com/repos/$REPO/releases/latest"

          ISO_URL=$(curl -s $API_URL \
            | jq -r '.assets[] | select(.name | endswith(".iso")) | .browser_download_url')

          echo "ISO URL: $ISO_URL"
          wget -P source-iso "$ISO_URL"


      - name: Set ISO variables
        run: |
          ISO_NAME=$(ls source-iso/*.iso | xargs -n1 basename)
          BASE_NAME=${ISO_NAME%.iso}
          TAG_NAME=${BASE_NAME}-system-ota
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Extract ISO
        run: |
          cd source-iso
          bsdtar -xf *.iso -C ../iso
          cd ..

      - name: Extract os-release from airootfs
        run: |
          mkdir -p iso/temp-mnt
          unsquashfs -f -no-xattrs -d iso/temp-mnt iso/arch/x86_64/airootfs.sfs

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.TAG_NAME }}
          files: |
            iso/arch/boot/x86_64/vmlinuz-*
            iso/arch/x86_64/*
            iso/temp-mnt/etc/os-release
